# = = = = = = = = = = = = = = = = = = = = = = = = = #
# GYMNASIUM ENVIRONMENT CONFIGS
# = = = = = = = = = = = = = = = = = = = = = = = = = #

# generic configs
[gymnasium]
epoch_time_horizon = 100                                    # [s]
use_random_seed = false                                     # true, false
random_seed = 0
normalize_observation = true                                # true, false
normalize_reward = true                                     # true, false

# observation space
[gymnasium.observation_space]
model_id = 1

# action space
[gymnasium.action_space]
model_id = 1

# reward function
[gymnasium.reward_function]
model_id = 1

# = = = = = = = = = = = = = = = = = = = = = = = = = #
# DYNAMIC SYSTEM CONFIGS
# = = = = = = = = = = = = = = = = = = = = = = = = = #

# generic configs
[dynamic_system]
sigma = 10
rho = 28
beta = 2.6666666666666666666666666666666667
state_dim = 3
input_dim = 3
state_boundaries = [[-20, -20, 0], [20, 20, 40]]
input_boundaries = [[-20, -20, 0], [20, 20, 40]]

# simulation configs
[dynamic_system.simulation]
integration_step = 0.01