[tool.poetry]
name = "ramen"
version = "0.1.0"
description = ""
authors = ["SlowWave <chrs.borgia@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.1.2"
scipy = "^1.14.1"
matplotlib = "^3.9.2"
gymnasium = "^1.0.0"
tomli = "^2.2.1"
plotly = "^5.24.1"
pyqt6 = "^6.8.1"
stable-baselines3 = {extras = ["extra"], version = "^2.5.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
